#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --polar disabled --unprivileged-port port --select-base /usr/libexec/device/services/app/minecraft/protocol.txt --select protocol"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart minecraft-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

