#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --hostname name --show-flags disabled --show-table name,port,protocol --flag X --polar disabled --unprivileged-port port --select-base /usr/libexec/device/services/app/minecraft/protocol.txt --select protocol"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

